### ISSUE TITLE
Add possibility to use different images for the header and the login logo

### ISSUE THREAD

**Issue by fpotier** [SciCatProject/frontend#1135]
### Summary
Atm, the frontend uses the asset named `site-logo.png` to display the facility's logo in the header bar and on the login page.
There is a hard coded behavior for the ESS to use another image for the header bar.

In the login HTML template:
```
<div class="login-container" fxLayoutAlign="center center">
...
          <img src="assets/images/site-logo.png" />
...
```

And in the header HTML template:
```
<ng-template [ngIf]="facility === 'ESS'" [ngIfElse]="otherFacility">
        <img class="logo" src="../../../assets/images/esslogo-white.png" />
</ng-template>
<ng-template #otherFacility>
        <img class="logo" src="../../../assets/images/site-logo.png" />
</ng-template>
...
```

I need to do the same thing for SOLEIL so I suggest to simply use two differents images instead of hard coding the behavior (facilities using the same image for both could then mount the  image on two different paths)

**Comment by nitrosx** [comment]
I second that!!!
