### ISSUE TITLE
Move the 'free text' search up to a more prominent part of the main scicat page

### ISSUE THREAD

**Issue by nitrosx** [SciCatProject/frontend#1147]
### Summary
Move the 'free text' search field  right below the header and expand it to user the full width of the view port

This issue has been created from backend issue [#609](/SciCatProject/scicat-backend-next/issues/609)

**Comment by nitrosx** [comment]
![20230719_161143](https://github.com/SciCatProject/scicat-backend-next/assets/822780/0f32d877-fe9a-4378-bb95-742439e5c948)

**Comment by Ingvord** [comment]
@nitrosx could you please extend my rights so I can assign myself to this issue? Thanks

**Comment by nitrosx** [comment]
@Ingvord this is now assigned to you.
BTW, you are part of the admin team for this project, you should be able to assign this issue to yourself, but I'm not familiar with github permissions and we might have the wrong settings.

**Comment by Ingvord** [comment]
Closed via #1426
