### ISSUE TITLE
Add a "Search" or "Apply" button to the text entry field

### ISSUE THREAD

**Issue by nitrosx** [SciCatProject/frontend#1148]
### Summary
Add a "Search" or "Apply" button to submit the search to the backend.
This is so that the search and filters are only applied to the main dataset list when this is pressed, or the enter key is pressed on the open search text.

This issue has been created from backend issue [#608](/SciCatProject/scicat-backend-next/issues/608)

**Comment by nitrosx** [comment]
![20230719_161143](https://github.com/SciCatProject/scicat-backend-next/assets/822780/12b53aa5-f0a6-4f89-aad1-dfe52a03fb60)

**Comment by Ingvord** [comment]
Closed via #1426
