### ISSUE TITLE
Frontend Configuration Mechanisms

### ISSUE THREAD

**Issue by dylanmcreynolds** [SciCatProject/frontend#1186]
In #915, two different mechanisms were introduced to provide a `config.json` to the frontend. At ALS we use the mechanism where we mount it into the `frontend` container under` /usr/share/nginx/html/assets/config.json`.

While migrating to the new backend, we found that this is no longer an option. The `app.config.service` first [asks the server](https://github.com/SciCatProject/frontend/blob/4f57ad8ffb5377f92af23de47f73640d0c7eb129/src/app/app-config.service.ts#L97) if the config exists. If it does, it does not look for it in the frontend. But then in this [backend PR](https://github.com/SciCatProject/scicat-backend-next/pull/442) the ESS config was added to be always delivered by the backend, so the frontend is never asked.

I do not have a strong opinion about where to put this file but the SciCat community should decide if we support both methods or just one, and then make sure that whatever we support works.

**Comment by bpedersen2** [comment]
Yes, you now  need to mount your config into the backend container( as  /home/node/app/dist/src/config/frontend.config.json), the frontend now  just needs the API url.

**Comment by dylanmcreynolds** [comment]
But that means that everyone has to mount in both places, frontend to get the api url and backend to get the file?

**Comment by bpedersen2** [comment]
Actually no, the initial URL is hardcoded and assumes that FE and BE are serverd on the same domain.

This also means you could in theory server different backends with a singel  FE deployment(using hostname based routing).

**Comment by bpedersen2** [comment]
The fallback is there (only) for proxyless dev setups, where the BE is serverd on a different port. Then you need to serve the config on the  FE.

**Comment by dylanmcreynolds** [comment]
Relooking at this old issue. Is it tru that  the only reason to support frontend configuration in the front end at all now is if your api url were non-standard, in which case you'd have to put in the config.json in the front end to pick it up.
