### ISSUE TITLE
Replace PID condition configuration with two runtime PID filters

### ISSUE THREAD

**Issue by Ingvord** [SciCatProject/frontend#1466]
After #1465 we may want to remove PID condition from the configuration and instead have two dedicated instances of PID filter

**Comment by nitrosx** [comment]
Just to confirm that I understand correctly, you would like to remove the current PID filter and add multiple filters each implementing a specific functionality, like `PID equal to`, or `PID containing`.

**Comment by Ingvord** [comment]
Yes, exactly. You got it right, @nitrosx !

**Comment by nitrosx** [comment]
Go for it!!!
