### ISSUE TITLE
Datasets: Pagination broken with new search interface

### ISSUE THREAD

**Issue by bpedersen2** [SciCatProject/frontend#1502]
On current master the pagination does not work anymore: The indicator does react (1-25 => 26- 50 etc,) but the displayed datasets do not change.

### Steps to Reproduce
Hava test instance with sufficient datasets to trigger pagination.

### Extra Details

reverting f137de831a89dfd4a0902dfc520d8d74c382b357. (#1434) does fix pagination, so it seems to be linked to the new search interface.

**Comment by bpedersen2** [comment]
@Ingvord , can you take a look?

**Comment by Ingvord** [comment]
@bpedersen2 thanks for reporting! Apparently pagination now also requires clicking on the "search" button %)

**Comment by Ingvord** [comment]
Should be fixed via #1503 

I'll open a follow up issue to cover pagination with cypress tests
