### ISSUE TITLE
Search functionality fails after filter reset.

### ISSUE THREAD

**Issue by Junjiequan** [SciCatProject/frontend#1568]
## Issue Name
Search functionality fails after filter reset.

### Summary
After clicking the "Reset Filters" button, the search function no longer works with the same PID value.

https://github.com/user-attachments/assets/27d4de80-49b6-4d5c-9a29-94cf94c457bc

### Steps to Reproduce

1. Apply a search using a specific PID value.
2. Click the "Reset Filters" button.
3. Attempt to search again using the same PID value.

### Current Behaviour
The search does not return any query results after filters are reset.

### Expected Behaviour
The search should return query results when using the same PID value after resetting the filters.

### Extra Details
Provide all the relevant details related to this issues. Include screenshot, wireframes and mockups if helpful.

__PS__: make ssure to add the proper tags to the issue

**Comment by Ingvord** [comment]
@Junjiequan Thanks for reporting!

Should be fixed via #1569
