### ISSUE TITLE
Frontend topics related to release-jobs

### ISSUE THREAD

**Issue by despadam** [SciCatProject/frontend#1590]
- Discuss with site that uses the `files` property whether changing
```
 job.datasetList = {
              pid: "",
              files: [],
            }
```
to `job.datasetIds = ["pid1", "pid2" ]` would still work for them (see `src/app/datasets/admin-tab/admin-tab.component.ts`)
- `JobClass` extends `OwnableClass`, but is field `isPublished` needed for a job?
- Should `ownerUser` in the Job schema be renamed to `owner` (to match `Dataset.owner`) and should it be required?

- Up to now I think the backend was backwards-compatible with v3. We should clearly indicate in the README that it requires scicat-backend-next.

_Originally posted by @sbliven in https://github.com/SciCatProject/frontend/pull/1585

**Comment by despadam** [comment]
Actions:

1. We mark `isPublished` fields as optional in the fe
2. Preserve the `ownerUser` field in Job Schema, as it checked and must be a valid SciCat user, while the `owner` in the Dataset schema can be any string. Naming them differently signifies this difference. Lastly, `ownerUser` should be a required field.

**Comment by sofyalaski** [comment]
I think the logic was that the `ownerUser` is not a required property. For instance, admin can create a job for someone and it need not be restricted to a specific user but just a group.

**Comment by despadam** [comment]
Should we enforce job types like so?
```
export enum JobType {
  Archive = "archive",
  Retrieve = "retrieve",
  Public = "public",
}
```

**Comment by despadam** [comment]
PR: https://github.com/SciCatProject/frontend/pull/1616

**Comment by despadam** [comment]
TODO: #1619

**Comment by despadam** [comment]
PR https://github.com/SciCatProject/frontend/pull/1616 was closed because it was covered when rebasing `release-jobs` to `master`: https://github.com/SciCatProject/frontend/tree/wip-rebase-release-jobs
