### ISSUE TITLE
don't allow publication of already public data

### ISSUE THREAD

**Issue by garethcmurphy** [SciCatProject/frontend#458]
### Extra Details

Here you should include details about the system (if it is unique) and possible information about a fix (feel free to link to code where relevant). Screenshots/GIFs are also fine here.

**Comment by lukegorman** [comment]
not sure about this one as there is value in grouping datasets together regardless of weather they have been published before or not

**Comment by garethcmurphy** [comment]
I think a new group is fine, but a PI user accidentally generating duplicate PIDs for same dataset could be avoided. Could also be an alert
