### ISSUE TITLE
Fix/Add sharing of datasets

### ISSUE THREAD

**Issue by bolmsten** [SciCatProject/frontend#808]
## Use Case

There exist multiple use cases when it comes to sharing of data, they range from sharing all data on a proposal for a large group, to sharing a single dataset with an individual. 

It is proposed to start with the use case of sharing a number of dataset with one or more people. A PI or Co-proposer that has access rights to the data can select one or more users to get access to a selected number of datasets by adding their email addresses. It should also be possible to revoke access given to a user.

Different sites will have different requirements when it comes to who is allowed to share data, this could be fixed by leveraging the policy system in scicat.

### Proposed solution

Some functionality already exist in SciCat that tries to cater to the above mentioned use case, it is however not in a production ready state and is missing some features. 

As seen below a user can select a number of datasets and through the shopping cart select share, this will prompt the user to fill in a email address for an already registered user in SciCat. If the user does not have a registered account a message should be shown informing of this. It should also be possible to add multiple people in the modal shown.

<img width="1434" alt="Screenshot 2021-07-28 at 13 29 52" src="https://user-images.githubusercontent.com/6403388/127315336-d894e2c7-8e18-4576-bf14-69ec764f756b.png">

In the dataset view a user can se who has been shared a specific dataset and has the possibility to remove a user.

<img width="1436" alt="Screenshot 2021-07-28 at 15 27 38" src="https://user-images.githubusercontent.com/6403388/127330812-a1126092-dd0b-4595-beb8-fc92af3d31c5.png">

### Technical

Currently access and owner groups exist to control who can see what data, one option would be to extend this functionality and create groups on the fly when sharing datasets. This group would than be added to the concerned datasets under shared group. This solution would however require a significant amount of development as new GUI and logic would need to be developed for the handling of groups.

Another option would be to add selected users directly on the dataset, this would eliminate the need for groups and make for a simplified workflow. A user can than visit a dataset and remove a user if needed.

----- Add more information here about what is currently possible to do in catamel and the best technical way forward ----

Each site would need to handle what it means for a user to be given access to a dataset in there specific infrastructure. This becomes important as users would want to access data through other systems than scicat.

### Open questions

How can we let users select people to share with without breaking GDPR regarding sharing of user data?

Can we add people instead of groups directly on datasets without major refactoring?

**Comment by dylanmcreynolds** [comment]
I think we should remove the current UI for sharing until a working implementation is built. It's fairly misleading right now.

**Comment by nitrosx** [comment]
Addressed with PR #838
