### ISSUE TITLE
Add child routes for dataset details tabs

### ISSUE THREAD

**Issue by stephan271** [SciCatProject/frontend#848]
## Issue Name
ChildRoutesDatasetDetails

### Summary
When switching between Tabs in the dataset details view the URL should reflect this state change by adding child routes

### Extra Details

Prerequisite for fixing #847

**Comment by nguyenlinhlinh** [comment]
you mean something like this https://scicat-test.maxiv.lu.se/datasets/[pid]/datafiles, https://scicat-test.maxiv.lu.se//datasets/20.500.12269%2F353bb674-1bbf-4829-9cdb-e4f1b0d58142/reduce?

**Comment by nguyenlinhlinh** [comment]
WIP

**Comment by stephan271** [comment]
Thanks for taking this up !
