### ISSUE TITLE
How do you set up to allow downloading of public dataset with huge files? 

### ISSUE THREAD

**Issue by nguyenlinhlinh** [SciCatProject/frontend#864]
## Issue Name
Asking for ideas and maybe there are common things that can be implemented.
### Summary
At MAXIV we are trying to create a workflow to allow downloading dataset anonymously. We want to support downloading dataset from Globus. Our public storage has space limitation so we cannot have all public datasets in there but they need to be copied on demand and removed after some months.
The workflow we are intended to do:
- The user open the public dataset he/she wants to download and click on the download button and enter the email adress. 
- Catanie create a job by sending http request to the backend. 
- Catamel receive the http request, create a job message and push it to msg queue. 
- Our copy service reads the msg, performs the work and communicates the result back to Catamel. 
- Catamel notifies the user that dataset is available for download in Globus.

The problem we run into now is that creating a job in Catamel requires authentication so we are thinking of a workaround. 

### Questions
- How does the anonymous dataset downloading looks like at your facilities or how do you imagine it should look like if you haven't set it up yet?

**Comment by nitrosx** [comment]
@nguyenlinhlinh : I will chat with our team and post thoughts here. Also, I will make sure that we discuss it in one of the SciCat meetings.

**Comment by dylanmcreynolds** [comment]
This is related to a feature request https://github.com/SciCatProject/frontend/issues/817
