### ISSUE TITLE
Enter key in text field search produces [object Event] in Chrome

### ISSUE THREAD

**Issue by dylanmcreynolds** [SciCatProject/frontend#877]
### Summary
On Ubuntu desktop, I see this issue in Chromium but not Firefox. This has been reported by a user who I believe is using Mac and Chrome.

The enter key in the Text search field is extraneous...nobody need use it. However, if you type the `Enter` key in the text field, whatever you typed is replaced by `[object Event]`

### Steps to Reproduce
1. login in
2. Enter text in the `Text Search` field
3. Type the `Enter` key

Observe that your text is replaced by `[object Event]`

**Comment by dylanmcreynolds** [comment]
Just  to add that hitting the `Enter` is a pretty natural thing to do. In this case, doing so makes the search not work, giving some users the impression that it's broken.

**Comment by nitrosx** [comment]
@dylanmcreynolds : I was able to reproduce the issue.
Interesting enough, There are no errors in the console.
Any suggestion on how to troubleshoot the issue?

**Comment by dylanmcreynolds** [comment]
@LAShemilt, many thanks.

**Comment by nitrosx** [comment]
That makes sense as Edge is based on Chromium which share the same code base as Chrome.

**Comment by LAShemilt** [comment]
I also checked this on Safari, as a Mac user was complaining to me that the search did not work. We get the [objectEvent] in the text pane on Safari too.
