### ISSUE TITLE
Rename catamel to backend and catanie to frontend

### ISSUE THREAD

**Issue by stephan271** [SciCatProject/frontend#884]
## Issue Name
RenameRepoNames

### Summary
All appearances of "catamel", "CATAMEL" and "catanie, "CATANIE" etc , such as in deployment scripts, need to be adjusted to the new repo naming

**Comment by nitrosx** [comment]
@stephan271 : I'm closing this ticket as I'm currently working on it.
The PR should be ready next week.

**Comment by stephan271** [comment]
:+1:
