### ISSUE TITLE
curiosity: RawDataset PrincipalInvestigator vs. DerivedDataset investigator

### ISSUE THREAD

**Issue by toqduj** [SciCatProject/frontend#902]
Out of curiosity, where does the difference in RawDataset's "PrincipalInvestigator" and DerivedDataset's "investigator" come from?

**Comment by toqduj** [comment]
fair enough. Do these have any relation to the User class? i.e. are they supposed to be linked to instances of User? That way we wouldn't have to duplicate e-mail addresses etc.

**Comment by stephan271** [comment]
No, no relation to the User class , because it may well be a person otherwise not known to the SciCat system, depending on the setup of the connected IDMs.

**Comment by stephan271** [comment]
Just a test
