### ISSUE TITLE
Tree representation of sample characteristics 

### ISSUE THREAD

**Issue by linupi** [SciCatProject/frontend#928]
## Issue Name
Tree representation of sample characteristics for nested sample metadata.

### Summary
While there is a tree-like representation for `ScientificMetadata` in the _Dataset-view_, that can that can be enabled via `metadataStructure: "tree"` in the _environment.ts_ file, I couldn't find a simmiar feature for the corresponding metadata section of `Sample`.
 
### Steps to Reproduce
Create a new sample with tree-like structure in `Characteristics` .

### Current Behaviour
(see screenshot) The json string of the nested structure is displayed as `value` in the table.

### Expected Behaviour 
A view like the one for `ScientificMetadata` of `Dataset` with `metadataStructure: "tree"` in config.

### Extra Details
![sample_characteristics](https://user-images.githubusercontent.com/3169764/156999528-f86ace2f-377c-48f6-9abf-96bb1acb661f.png)

**Comment by nguyenlinhlinh** [comment]
I only implemented tree structure for scientific metadata as a solution for MAXIV and PSI at the beginning. If it is useful and the SciCat organization allows I can make it available for Sample too since it is implemented in a way that we can easily reuse the code in different part as needed.

**Comment by nitrosx** [comment]
@nguyenlinhlinh : Thank you. 
Do you know when we should expect a PR for this?

**Comment by nguyenlinhlinh** [comment]
@nitrosx Maybe some time next week.
