### ISSUE TITLE
Bug with Sign In button

### ISSUE THREAD

**Issue by nguyenlinhlinh** [SciCatProject/frontend#939]
## Issue Name
Bug with Sign In button
### Summary
When user view a private dataset without logging in the user get message "Dataset not found". The user then click on Sign in button to log in but nothing happens. No log in page shows up.
### Steps to Reproduce
- Log in and open a private dataset.
- Copy the url of the private dataset.
- Log out.
- Paste the url to your webbrowser.
- Click on Sign In button
### Current Behaviour
No log in page shows up.
### Expected Behaviour
Log in page should show up.

**Comment by dylanmcreynolds** [comment]
I just got a report from a user about this after upgrading from a very old version to the dev branch from last Wednesday or Thursday.

**Comment by nitrosx** [comment]
I was not able to reproduce it but we have not updated our production environment recently.

**Comment by nitrosx** [comment]
@nguyenlinhlinh  would you mind provide more details on the issue? Thanks

**Comment by nguyenlinhlinh** [comment]
Not sure how I best can explain this but I will try.
For a dataset there is several [routes](https://github.com/SciCatProject/frontend/blob/develop/src/app/app-routing/lazy/dataset-details-dashboard-routing/dataset-details-dashboard.routing.module.ts). 
For route [/datasets/:id ](https://github.com/SciCatProject/frontend/blob/f7e3ab286bfeb00e911a529b534f66684a18a6d7/src/app/app-routing/lazy/dataset-details-dashboard-routing/dataset-details-dashboard.routing.module.ts#L16) there is a guard called `LeavingPageGuard`. This guard check if user has unsaved changes in `scientificMetada`.
When the user try to leave dataset detail page the code from this guard is executed [here](https://github.com/SciCatProject/frontend/blob/f7e3ab286bfeb00e911a529b534f66684a18a6d7/src/app/app-routing/pending-changes.guard.ts#L26).
When the user click on "Sign On" button means leaving dataset detais page the  code for `LeavingPageGuard` is executed and throws an exception `component is null`. Since js throws an exception nothing happens in the user interface (The user is not redirected to Log In page).


[This code](https://github.com/SciCatProject/frontend/blob/f7e3ab286bfeb00e911a529b534f66684a18a6d7/src/app/app-routing/pending-changes.guard.ts#L26) throws exception because component is null.
Now you ask why the component is null? It is because when I added extra routes to dataset details (`/datafiles`, `/reducer` ...) these routes have a requirement that the user interface should only show the datafiles-tab, reduce-tab, etc if the dataset exists and if user is logged in and has read/write access to the dataset. To achieved this requirement I added this code from [line 1-22](https://github.com/SciCatProject/frontend/blob/develop/src/app/datasets/dataset-details-dashboard/dataset-details-dashboard.component.html). In short the code means if dataset is not `null` or `undefined` return component depend on the route. 
Since the user is not logged in the request to see private dataset will return `dataset = null`, therefore no component is initialized/returned => `component = null`. As a result this [line](https://github.com/SciCatProject/frontend/blob/f7e3ab286bfeb00e911a529b534f66684a18a6d7/src/app/app-routing/pending-changes.guard.ts#L26) throws exception.
Let me know if it is still unclear.
