### ISSUE TITLE
Add copy buttons

### ISSUE THREAD

**Issue by jl-wynen** [SciCatProject/frontend#987]
## Add copy buttons

It would be nice to have buttons next to some / all fields to copy them to clipboard. This already exists for the token. It would especially help with dataset PIDs in order to copy them to a client software.

**Comment by bpedersen2** [comment]
In the dataset details, there is a copy-button for the pid
![screenshot-scicat k8s frm2 tum de-2023 09 05-10_43_43](https://github.com/SciCatProject/frontend/assets/5336494/96b43f10-c1c4-4846-89dd-cdf34c32ec76)

**Comment by jl-wynen** [comment]
True. This was added after I opened the issue but I forgot to close it.
